server:
  port: 0

spring:
  application:
    name: mscreditanalizer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource: url=jdbc:h2:mem:testdb

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

mq:
  queue:
    card-issuing-request: card-issuing-request
