services:
  debug:
    image: alpine:latest
    container_name: debug
    command: ["sh", "-c", "while true; do sleep 30; done"]
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq-data:/opt/data/db
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak
    environment:
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        KC_HTTP_PORT: 8081
    ports:
      - "8081:8081"
    command: ["start-dev"]
    volumes:
      - keycloak-data:/opt/data/db
    networks:
      - backend

  eureka:
      build:
        context: ./discovery-server
      container_name: eureka
      ports:
        - "8761:8761"
      environment:
        SERVER_PORT: 8761
        SERVER_HOSTNAME: eureka
        EUREKA_INSTANCE_HOSTNAME: localhost
        AUTH_USERNAME: admin
        AUTH_PASSWORD: admin
      networks:
        - backend

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    environment:
      EUREKA_SERVER: http://admin:admin@eureka:8761/eureka 
      OAUTH2_ISSUER_URI: http://keycloak:8081/realms/bankauthprovider
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - backend

  mscards:
    build:
        context: ./ms-cards
    container_name: mscards
    environment:
      RABBITMQ_SERVER: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_CARD_ISSUE_QUEUE: card-issuing-request 
      EUREKA_SERVER: http://admin:admin@eureka:8761/eureka 
    networks:
          - backend

  mscreditanalizer:
    build:
        context: ./ms-creditAnalizer
    container_name: mscreditanalizer
    environment:
      EUREKA_SERVER: http://admin:admin@eureka:8761/eureka 
      RABBITMQ_SERVER: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_CARD_ISSUE_QUEUE: card-issuing-request 
    networks:
          - backend

  msclients:
    build:
        context: ./ms-client
    container_name: msclients
    environment:
      EUREKA_SERVER: http://admin:admin@eureka:8761/eureka 
    networks:
          - backend

volumes:
  rabbitmq-data:
  keycloak-data:

networks:
  backend:
    driver: bridge
