server:
  port: ${SERVER_PORT}

spring:
  application:
    name: msgateway
  cloud:
    gateway:
        server:
          webflux:
            discovery:
              locator:
                enabled: true
                lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI} 

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER}
