server:
  port: 8082

spring:
  application:
    name: msgateway
  cloud:
    gateway:
        server:
          webflux:
            discovery:
              locator:
                enabled: true
                lowe-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bankauthprovider

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

mq:
  queue:
    card-issuing-request: card-issuing-request
