server:
  port: 0

spring:
  application:
    name: mscards
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

mq:
  queue:
    card-issuing-request: card-issuing-request

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
