run-server:
	./discovery-server/mvnw -f ./discovery-server/pom.xml spring-boot:run

run-gateway:
	./gateway/mvnw -f ./gateway/pom.xml spring-boot:run

run-client:
	./ms-client/mvnw -f ./ms-client/pom.xml spring-boot:run

run-card:
	./ms-carts/mvnw -f ./ms-carts/pom.xml spring-boot:run

run-credit:
	./ms-creditAnalizer/mvnw -f ./ms-creditAnalizer/pom.xml spring-boot:run
