@urlclient = "http://localhost:8080/clients"
@urlcard = "http://localhost:8080/cards"
@urlcredit = "http://localhost:8080/credit-analizer"

POST {{urlclient}}
Content-Type: application/json

{
    "name": "erick",
    "cpf": "12345678900",
    "age": 30
}

###

GET {{urlclient}}?cpf=12345678900

###

POST {{urlcard}}
Content-Type: application/json

{
    "name": "Gold Card",
    "brand": "VISA",
    "income": 5000,
    "creditLimit": 2000
}

###

GET {{urlcredit}}/12345678900
