server:
  port: 0

spring:
  application:
    name: msclients
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
